const npcOccupations = [
    'advocate',
    'astrologer',
    'cartographer',
    'judge',
    'scholar',
    'scribe',
    'student',
    'writer',
    'duke',
    'marquess',
    'count',
    'viscount',
    'baron',
    'greatchief',
    'warchief',
    'chief',
    'elder',
    'architect',
    'bricklayer',
    'carpenter',
    'mason',
    'plasterer',
    'roofer',
    'acolyte',
    'priest',
    'shaman',
    'alchemist',
    'armorer',
    'baker',
    'basket weaver',
    'blacksmith',
    'bookbinder',
    'bowyer',
    'brewer',
    'butcher',
    'cobbler',
    'cook',
    'cooper',
    'dyer',
    'engraver',
    'furniture maker',
    'glass blower',
    'goldsmith',
    'instrument maker',
    'inventor',
    'jeweler',
    'leatherworker',
    'locksmith',
    'painter',
    'paper maker',
    'potion brewer',
    'potter',
    'rope maker',
    'rug maker',
    'sculptor',
    'ship builder',
    'silversmith',
    'skinner',
    'soapmaker',
    'tailor',
    'tanner',
    'tinker',
    'toymaker',
    'weaponsmith',
    'weaver',
    'wheelwright',
    'woodcarver',
    'bandit',
    'burglar',
    'pickpocket',
    'pirate',
    'raider',
    'acrobat',
    'bather',
    'jester',
    'minstrel',
    'prostitute',
    'storyteller',
    'crop farmer',
    'gatherer',
    'herder',
    'banker',
    'moneychanger',
    'pawnbroker',
    'tax collector',
    'healer',
    'herbalist',
    'midwife',
    'brothel keeper',
    'innkeeper',
    'restaurantier',
    'tavern keeper',
    'day laborer',
    'miner',
    'porter',
    'beer merchant',
    'bookseller',
    'caravanner',
    'dairy seller',
    'fishmonger',
    'florist',
    'grain merchant',
    'grocer',
    'haberdasher',
    'hay merchant',
    'livestock merchant',
    'military outfitter',
    'miller',
    'peddler',
    'spice merchant',
    'tobacco merchant',
    'used clothier',
    'warehouser',
    'wine merchant',
    'woodseller',
    'wool merchant',
    'bounty hunter',
    'city guard',
    'private guard',
    'mercenary',
    'soldier',
    'village guard',
    'explorer',
    'fisher',
    'hunter',
    'sailor',
    'trapper',
    'traveler',
    'diplomat',
    'official',
    'politician',
    'town crier',
    'barber',
    'carriage driver',
    'gardener',
    'groom',
    'guide',
    'inn server',
    'launderer',
    'page',
    'rat catcher',
    'restaurant server',
    'tavern server',
    'beggar',
    'housespouse',
];

module.exports = npcOccupations;
